book/urls.py
from django.contrib import admin
from django.urls import path
from .views import *

app_name = 'book'

urlpatterns = [
    path('', UserDetailsCreateView.as_view(), name='welcome_page'),
    path('<int:user_id>/pdf/preview', PDFPreviewView.as_view(), name='pdf_preview'),
    path('<int:pk>/user/feedback', FeedbackView.as_view(), name='feedback'),

]

preface/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('book.urls')),

]

book/models.py
from django.db import models
from django.core.validators import RegexValidator


class UserDetails(models.Model):
    name = models.CharField(max_length=256, blank=False, null=False)
    views = models.IntegerField(unique=False, blank=True, null=True)
    reviews = models.CharField(max_length=1024, blank=True, null=True)

book/views.py
from django.shortcuts import reverse, render, HttpResponseRedirect
from django.views.generic.edit import CreateView, View, UpdateView
from .models import UserDetails
from easy_pdf.views import PDFTemplateView
from django import forms


class UserDetailsCreateView(CreateView):
    model = UserDetails
    template_name = "welcomePage.html"
    fields = ['name']
    user_name = None

    def get_success_url(self):
        user_id = self.existing_user_view(self.user_name)[0].id
        return reverse('book:pdf_preview', kwargs={'user_id': user_id})

    def existing_user_view(self, name):
        self.user_name = name
        if UserDetails.objects.filter(name=name).count() > 0:
            return UserDetails.objects.filter(name=name)
        else:
            return None

    def form_valid(self, form):
        user_data = form.save(commit=False)
        altered_name = user_data.name.upper()
        existing_user = self.existing_user_view(altered_name)
        if existing_user is None:
            user_data.views = 1
            user_data.name = altered_name
            user_data.save()
            return super().form_valid(form)
        else:
            existing_user.update(views=existing_user[0].views + 1)
            return HttpResponseRedirect(reverse('book:pdf_preview', kwargs={'user_id': existing_user[0].id}))

    def get_context_data(self, *args, **kwargs):
        context = super().get_context_data(*args, **kwargs)
        return context


class PDFPreviewView(View):
    template_name = "pdfPreviewPage.html"

    def get(self, request, user_id):
        user_existing_name = UserDetails.objects.filter(id=user_id)[0].name
        context = {}
        if "SHAMA" in user_existing_name or "SHAMA KASHYAP" in user_existing_name or "SHAMAKASHYAP" in user_existing_name:
            context['user_name'] = 'shama'
        context['user_id'] = user_id
        return render(request, self.template_name, context)


class FeedbackView(UpdateView):
    template_name = "feedback.html"
    model = UserDetails
    fields = ('reviews',)

    def get_success_url(self):
        return reverse('book:welcome_page')

    def get_form(self, form_class=None):
        form = super(FeedbackView, self).get_form(self.get_form_class())
        form.fields['reviews'].widget = forms.Textarea()
        return form

    def get_context_data(self, *args, **kwargs):
        context = super().get_context_data(*args, **kwargs)
        context['thanks_message'] = "Thanks for reading. Have a great day :)"
        return context

templates/base.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>1000 untold words</title>

    <link href="//maxcdn.bootstrapcdn.com/bootstrap/4.1.1/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">
    <script src="//cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
    <script src="//maxcdn.bootstrapcdn.com/bootstrap/4.1.1/js/bootstrap.min.js"></script>

    <script>
         {% block script_block %}

    {% endblock %}



    </script>
    <style>

    {% block style_block %}

    {% endblock %}







    </style>
</head>
<body>
{% block body_block %}

{% endblock %}
</body>
</html>

templates/feedback.html
{% extends "base.html" %}
{% load staticfiles %}
{% load widget_tweaks %}

{% block style_block %}
{% endblock %}


{% block body_block %}
<div id="login">
    <div class="container">
        <div id="login-row" class="row justify-content-center align-items-center">
            <div id="login-column" class="col-md-6">
                <div id="login-box" class="col-md-12">
                    <form id="login-form" class="form" action="" method="post">
                        <h5 class="text-center text-info">Provide your valuable review</h5>
                        {% csrf_token %}

                        {% for field in form %}
                        {% if field.errors %}
                        <div class="form-group">
                            <label for="id_{{ field.name }}" class="text-info">{{ field.label }}</label><br>

                            {{ field|attr:"class:form-control" }}
                            <span class="help-block">
                            {% for error in  field.errors %}{{ error }}{% endfor %}
                        </span>
                        </div>
                        {% else %}
                        <div class="form-group">
                            <label for="id_{{ field.name }}" class="text-info">{{ field.label }}</label><br>
                            {{ field|attr:"class:form-control" }}
                            {% if field.help_text %}
                            <p class="help-block">
                                <small>{{ field.help_text }}</small>
                            </p>
                            {% endif %}
                        </div>
                        {% endif %}
                        {% endfor %}
                        <button id="proceed_btn" style="float:right;background-color:#17a2b8;" class="btn btn-primary"
                                type="submit"> Submit
                        </button>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

templates/pdfPreviewPage.html
{% extends "base.html" %}
{% load staticfiles %}
{% load widget_tweaks %}

{% block style_block %}
#embed_pdf{
padding-left:30%;
}
{% endblock %}


{% block body_block %}

<div class="modal fade" id="show_message" role="dialog">
    <div class="modal-dialog modal-lg" style="width:100%;">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal">&times;</button>
                <h4 class="modal-title"></h4>
            </div>
            <div class="modal-body">
                <p>
                    Hey Shama, </p><br/>
                <p>
                    Hope you're doing great. Before making you either bored or excited or curious, let me wish you for
                    your birthday.

                    Many many happy returns of the day. Let you be blessed with all the happiness in the world :)
                    Keep Smiling with the same boy cut hairdo :) </p>

                <p>
                    Hope you would enjoy this very short journey.
                </p>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-default" data-dismiss="modal">Continue</button>
            </div>
        </div>
    </div>
</div>


<iframe src="{% static 'pdf/preface.pdf' %}" id="pdf" style="width:100%; height:800px;" frameborder="0"></iframe>
<form action="{% url 'book:feedback' user_id %}" method="GET">
    {% csrf_token %}
    <button style="float:right; margin-right:10%; background-color:#17a2b8" class="btn btn-success" type="submit"> Click
        here to provide review
    </button>
</form>
<!--<a href="#" data-toggle="modal" data-target="#show_message"><i class="fa fa-plus"></i> show message </a>-->


<script type="text/javascript">
{% if user_name == "shama" %}

 $(window).on('load',function(){
        $('#show_message').modal('show');
    });
{% endif %}



</script>
{% endblock %}

templates/welcomePage.html
{% extends "base.html" %}
{% load staticfiles %}
{% load widget_tweaks %}

{% block style_block %}
body {
margin: 0;
padding: 0;
background-color: #17a2b8;
height: 100vh;
}
#login .container #login-row #login-column #login-box {
margin-top: 120px;
max-width: 600px;
height: 350px;
border: 1px solid #9C9C9C;
background-color: #EAEAEA;
}
#login .container #login-row #login-column #login-box #login-form {
padding: 20px;
}
#login .container #login-row #login-column #login-box #login-form #register-link {
margin-top: -85px;
}

#proceed_btn{
float:right;
background-color: #17a2b8;
}
{% endblock %}

{% block body_block %}
<div id="login">

    <!--{% if thanks_message != None %}-->
    <!--<br/>-->
    <!--{% else %}-->
    <h3 class="text-center text-white pt-5">Welcome to the Preface</h3>
    <h3 class="text-center text-white pt-5">{{ thanks_message }}</h3>

    <!--{% endif %}-->

    <div class="container">
        <div id="login-row" class="row justify-content-center align-items-center">
            <div id="login-column" class="col-md-6">
                <div id="login-box" class="col-md-12">
                    <form id="login-form" class="form" action="" method="post">
                        <h5 class="text-center text-info">Please enter your full name and phone number to continue</h5>
                        {% csrf_token %}

                        {% for field in form %}
                        {% if field.errors %}
                        <div class="form-group">
                            <label for="id_{{ field.name }}" class="text-info">{{ field.label }}</label><br>

                            {{ field|attr:"class:form-control" }}
                            <span class="help-block">
                            {% for error in  field.errors %}{{ error }}{% endfor %}
                        </span>
                        </div>
                        {% else %}
                        <div class="form-group">
                            <label for="id_{{ field.name }}" class="text-info">{{ field.label }}</label><br>
                            {{ field|attr:"class:form-control" }}
                            {% if field.help_text %}
                            <p class="help-block">
                                <small>{{ field.help_text }}</small>
                            </p>
                            {% endif %}
                        </div>
                        {% endif %}
                        {% endfor %}
                        <!--<div id="register-link" class="text-right">-->
                        <!--<a href="#" onclick="$(this).closest('form').submit()" class="text-info">Proceed to-->
                        <!--Preview</a>-->
                        <!--</div>-->
                        <button id="proceed_btn" class="btn btn-primary" type="submit"> Proceed to Preview</button>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>


{% endblock %}